apiVersion: apps/v1
kind: Deployment
metadata:
name: retailops
spec:
replicas: 1
selector:
matchLabels:
app: retailops
template:
metadata:
labels:
app: retailops
spec:
containers:
- name: retailops
image: retailops-app
imagePullPolicy: Never
ports:
- containerPort: 3000